# Changes here will be overwritten by Copier
_commit: '5273708'
_src_path: https://github.com/oarepo/nrp-app-copier
languages: cs
repository_description: Catch-All repostitory for Czech scientific data
repository_human_name: CESNET Data Repository
