# Changes here will be overwritten by Copier
_commit: 8b0d6b1
_src_path: gh:oarepo/nrp-app-copier
languages: cs
repository_description: Catch-all repository for scientific datasets
repository_human_name: Data Harbour
