# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-License-Identifier: MIT

"""Create datarepo tables."""

import invenio_db
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = '1788081993'
down_revision = None
branch_labels = ('datarepo',)
depends_on = None


def _has_table(name):
    """Return True if the given table already exists."""
    return sa.inspect(op.get_bind()).has_table(name)


def _has_index(table_name, index_name):
    """Return True if the given index already exists on the table."""
    if not _has_table(table_name):
        return False
    indexes = sa.inspect(op.get_bind()).get_indexes(table_name)
    return any(idx['name'] == index_name for idx in indexes)


def _create_table_if_not_exists(name, *columns_and_constraints):
    """Create a table unless it already exists."""
    if not _has_table(name):
        op.create_table(name, *columns_and_constraints)


def _create_index_if_not_exists(index_name, table_name, columns, **kwargs):
    """Create an index unless it already exists."""
    if not _has_index(table_name, index_name):
        op.create_index(index_name, table_name, columns, **kwargs)


def _drop_index_if_exists(index_name, table_name):
    """Drop an index if it exists."""
    if _has_index(table_name, index_name):
        op.drop_index(index_name, table_name=table_name)


def _drop_table_if_exists(name):
    """Drop a table if it exists."""
    if _has_table(name):
        op.drop_table(name)


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_not_exists('datasets_metadata_version',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_datasets_metadata_version'))
    )
    _create_index_if_not_exists(op.f('ix_datasets_metadata_version_end_transaction_id'), 'datasets_metadata_version', ['end_transaction_id'], unique=False)
    _create_index_if_not_exists(op.f('ix_datasets_metadata_version_operation_type'), 'datasets_metadata_version', ['operation_type'], unique=False)
    _create_index_if_not_exists(op.f('ix_datasets_metadata_version_transaction_id'), 'datasets_metadata_version', ['transaction_id'], unique=False)
    _create_table_if_not_exists('datasets_parent_metadata',
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('workflow', sa.String(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_parent_metadata'))
    )
    _create_table_if_not_exists('datasets_draft_metadata',
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', invenio_db.shared.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_datasets_draft_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_datasets_draft_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['datasets_parent_metadata.id'], name=op.f('fk_datasets_draft_metadata_parent_id_datasets_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_draft_metadata'))
    )
    _create_table_if_not_exists('datasets_metadata',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_datasets_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_datasets_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['datasets_parent_metadata.id'], name=op.f('fk_datasets_metadata_parent_id_datasets_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_metadata'))
    )
    _create_table_if_not_exists('datasets_draft_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_datasets_draft_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['datasets_draft_metadata.id'], name=op.f('fk_datasets_draft_files_record_id_datasets_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_draft_files'))
    )
    _create_index_if_not_exists(op.f('ix_datasets_draft_files_object_version_id'), 'datasets_draft_files', ['object_version_id'], unique=False)
    _create_index_if_not_exists(op.f('ix_datasets_draft_files_record_id'), 'datasets_draft_files', ['record_id'], unique=False)
    _create_index_if_not_exists('uidx_datasets_draft_files_record_id_key', 'datasets_draft_files', ['record_id', 'key'], unique=True)
    _create_table_if_not_exists('datasets_draft_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_datasets_draft_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['datasets_draft_metadata.id'], name=op.f('fk_datasets_draft_media_files_record_id_datasets_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_draft_media_files'))
    )
    _create_index_if_not_exists(op.f('ix_datasets_draft_media_files_object_version_id'), 'datasets_draft_media_files', ['object_version_id'], unique=False)
    _create_index_if_not_exists(op.f('ix_datasets_draft_media_files_record_id'), 'datasets_draft_media_files', ['record_id'], unique=False)
    _create_index_if_not_exists('uidx_datasets_draft_media_files_record_id_key', 'datasets_draft_media_files', ['record_id', 'key'], unique=True)
    _create_table_if_not_exists('datasets_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_datasets_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['datasets_metadata.id'], name=op.f('fk_datasets_files_record_id_datasets_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_files'))
    )
    _create_index_if_not_exists(op.f('ix_datasets_files_object_version_id'), 'datasets_files', ['object_version_id'], unique=False)
    _create_index_if_not_exists(op.f('ix_datasets_files_record_id'), 'datasets_files', ['record_id'], unique=False)
    _create_index_if_not_exists('uidx_datasets_files_record_id_key', 'datasets_files', ['record_id', 'key'], unique=True)
    _create_table_if_not_exists('datasets_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_datasets_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['datasets_metadata.id'], name=op.f('fk_datasets_media_files_record_id_datasets_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets_media_files'))
    )
    _create_index_if_not_exists(op.f('ix_datasets_media_files_object_version_id'), 'datasets_media_files', ['object_version_id'], unique=False)
    _create_index_if_not_exists(op.f('ix_datasets_media_files_record_id'), 'datasets_media_files', ['record_id'], unique=False)
    _create_index_if_not_exists('uidx_datasets_media_files_record_id_key', 'datasets_media_files', ['record_id', 'key'], unique=True)
    _create_table_if_not_exists('datasets_parent_record_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['datasets_metadata.id'], name=op.f('fk_datasets_parent_record_state_latest_id_datasets_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['datasets_draft_metadata.id'], name=op.f('fk_datasets_parent_record_state_next_draft_id_datasets_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['datasets_parent_metadata.id'], name=op.f('fk_datasets_parent_record_state_parent_id_datasets_parent_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_datasets_parent_record_state'))
    )
    _create_table_if_not_exists('datasets_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_datasets_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['datasets_parent_metadata.id'], name=op.f('fk_datasets_parents_community_record_id_datasets_parent_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_datasets_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_datasets_parents_community'))
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_table_if_exists('datasets_parents_community')
    _drop_table_if_exists('datasets_parent_record_state')
    _drop_index_if_exists('uidx_datasets_media_files_record_id_key', 'datasets_media_files')
    _drop_index_if_exists(op.f('ix_datasets_media_files_record_id'), 'datasets_media_files')
    _drop_index_if_exists(op.f('ix_datasets_media_files_object_version_id'), 'datasets_media_files')
    _drop_table_if_exists('datasets_media_files')
    _drop_index_if_exists('uidx_datasets_files_record_id_key', 'datasets_files')
    _drop_index_if_exists(op.f('ix_datasets_files_record_id'), 'datasets_files')
    _drop_index_if_exists(op.f('ix_datasets_files_object_version_id'), 'datasets_files')
    _drop_table_if_exists('datasets_files')
    _drop_index_if_exists('uidx_datasets_draft_media_files_record_id_key', 'datasets_draft_media_files')
    _drop_index_if_exists(op.f('ix_datasets_draft_media_files_record_id'), 'datasets_draft_media_files')
    _drop_index_if_exists(op.f('ix_datasets_draft_media_files_object_version_id'), 'datasets_draft_media_files')
    _drop_table_if_exists('datasets_draft_media_files')
    _drop_index_if_exists('uidx_datasets_draft_files_record_id_key', 'datasets_draft_files')
    _drop_index_if_exists(op.f('ix_datasets_draft_files_record_id'), 'datasets_draft_files')
    _drop_index_if_exists(op.f('ix_datasets_draft_files_object_version_id'), 'datasets_draft_files')
    _drop_table_if_exists('datasets_draft_files')
    _drop_table_if_exists('datasets_metadata')
    _drop_table_if_exists('datasets_draft_metadata')
    _drop_table_if_exists('datasets_parent_metadata')
    _drop_index_if_exists(op.f('ix_datasets_metadata_version_transaction_id'), 'datasets_metadata_version')
    _drop_index_if_exists(op.f('ix_datasets_metadata_version_operation_type'), 'datasets_metadata_version')
    _drop_index_if_exists(op.f('ix_datasets_metadata_version_end_transaction_id'), 'datasets_metadata_version')
    _drop_table_if_exists('datasets_metadata_version')
    # ### end Alembic commands ###
